# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    displayName: CI Stage
    jobs: 
      - job: build
        displayName: Build
        steps:
          - script: |
              make nano
            displayName: 'make'
  - stage: CD
    displayName: CD stage
    jobs:
      - deployment: deploy
        displayName: Deploy
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo This is a deployment job
                  displayName: 'Deploy binary'