name: actions

on:

  pull_request:
    banches: [ "master" ]

  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run Makefile
           run: make4