name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install xmllint
      run: sudo apt-get install -y libncurses5-dev libncursesw5-dev libncurses*
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1

